#############################################################################
# Makefile for building: StrategyViewer.app/Contents/MacOS/StrategyViewer
# Generated by qmake (3.1) (Qt 6.5.0)
# Project:  StrategyViewer.pro
# Template: app
# Command: /Users/juliensolbach/Qt/6.5.0/macos/bin/qmake -o Makefile StrategyViewer.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug QMAKE_APPLE_DEVICE_ARCHS=arm64
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I../LIBS/common -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtSvg.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/macx-clang -F/Users/juliensolbach/Qt/6.5.0/macos/lib
QMAKE         = /Users/juliensolbach/Qt/6.5.0/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/juliensolbach/Qt/6.5.0/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/juliensolbach/Qt/6.5.0/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = StrategyViewer1.0.0
DISTDIR = /Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/StrategyViewer/.tmp/StrategyViewer1.0.0
LINK          = /Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=11.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/juliensolbach/Qt/6.5.0/macos/lib
LIBS          = $(SUBLIBS) -F/Users/juliensolbach/Qt/6.5.0/macos/lib -framework QtSvg -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = jsonhelperfunctions.cpp \
		link.cpp \
		main.cpp \
		mainwindow.cpp \
		node.cpp \
		playground.cpp \
		robot.cpp \
		toolboxscene.cpp qrc_ui.cpp \
		moc_link.cpp \
		moc_mainwindow.cpp \
		moc_node.cpp \
		moc_playground.cpp \
		moc_toolboxscene.cpp
OBJECTS       = jsonhelperfunctions.o \
		link.o \
		main.o \
		mainwindow.o \
		node.o \
		playground.o \
		robot.o \
		toolboxscene.o \
		qrc_ui.o \
		moc_link.o \
		moc_mainwindow.o \
		moc_node.o \
		moc_playground.o \
		moc_toolboxscene.o
DIST          = Images/vinyle_table_2023.png \
		config/commonActions.json \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/spec_pre.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/device_config.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/unix.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/mac.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/macx.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/sanitize.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/gcc-base.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/gcc-base-mac.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/clang.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/clang-mac.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/qconfig.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_core.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_core5compat.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_help.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_network.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_scxml.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_serialport.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_shadertools.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_statemachine.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qt_functions.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qt_config.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/macx-clang/qmake.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/exclusive_builds.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/sdk.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/toolchain.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/toolchain.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/default_pre.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/default_pre.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/resolve_config.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/default_post.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/default_post.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/objective_c.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qml_debug.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/mac.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/warn_on.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/permissions.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qt.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/resources_functions.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/resources.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/moc.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/unix/opengl.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/uic.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/unix/thread.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qmake_use.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/file_copies.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/rez.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/testcase_targets.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/exceptions.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/yacc.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/lex.prf \
		StrategyViewer.pro ../LIBS/common/shared_types.hpp \
		jsonhelperfunctions.h \
		link.h \
		mainwindow.h \
		node.h \
		playground.h \
		robot.h \
		toolboxscene.h jsonhelperfunctions.cpp \
		link.cpp \
		main.cpp \
		mainwindow.cpp \
		node.cpp \
		playground.cpp \
		robot.cpp \
		toolboxscene.cpp
QMAKE_TARGET  = StrategyViewer
DESTDIR       = 
TARGET        = StrategyViewer.app/Contents/MacOS/StrategyViewer

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 13.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode_13_0.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/StrategyViewer/.qmake.stash
EXPORT_VALID_ARCHS = arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/StrategyViewer/StrategyViewer.pro


include /Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

StrategyViewer.app/Contents/MacOS/StrategyViewer: ui_mainwindow.h $(OBJECTS)  
	@test -d StrategyViewer.app/Contents/MacOS/ || mkdir -p StrategyViewer.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: StrategyViewer.pro /Users/juliensolbach/Qt/6.5.0/macos/mkspecs/macx-clang/qmake.conf /Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/spec_pre.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/device_config.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/unix.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/mac.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/macx.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/sanitize.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/gcc-base.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/gcc-base-mac.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/clang.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/clang-mac.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/qconfig.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_core.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_core5compat.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_help.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_network.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_scxml.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_serialport.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_shadertools.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_statemachine.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qt_functions.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qt_config.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/macx-clang/qmake.conf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/exclusive_builds.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/sdk.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/toolchain.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/toolchain.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/default_pre.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/default_pre.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/resolve_config.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/default_post.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/default_post.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/objective_c.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qml_debug.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/mac.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/warn_on.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/permissions.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qt.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/resources_functions.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/resources.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/moc.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/unix/opengl.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/uic.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/unix/thread.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qmake_use.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/file_copies.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/rez.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/testcase_targets.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/exceptions.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/yacc.prf \
		/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/lex.prf \
		StrategyViewer.pro \
		ui.qrc \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtSvg.framework/Resources/QtSvg.prl \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Resources/QtGui.prl \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile StrategyViewer.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug QMAKE_APPLE_DEVICE_ARCHS=arm64
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/spec_pre.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/device_config.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/unix.conf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/mac.conf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/macx.conf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/sanitize.conf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/gcc-base.conf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/gcc-base-mac.conf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/clang.conf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/common/clang-mac.conf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/qconfig.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_ext_freetype.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_ext_libjpeg.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_ext_libpng.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_core.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_core5compat.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_core5compat_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_core_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_freetype_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_help.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_help_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_network.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_network_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_png_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_scxml.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_scxmlqml.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_serialbus.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_serialport.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_shadertools.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_statemachine.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_statemachine_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_statemachineqml.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_tools_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml_private.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qt_functions.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qt_config.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/macx-clang/qmake.conf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/exclusive_builds.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/sdk.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/toolchain.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/toolchain.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/default_pre.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/default_pre.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/resolve_config.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/default_post.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/default_post.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/objective_c.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qml_debug.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/mac.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/warn_on.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/permissions.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qt.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/resources_functions.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/resources.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/moc.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/unix/opengl.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/uic.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/unix/thread.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/qmake_use.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/file_copies.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/rez.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/mac/asset_catalogs.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/testcase_targets.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/exceptions.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/yacc.prf:
/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/lex.prf:
StrategyViewer.pro:
ui.qrc:
/Users/juliensolbach/Qt/6.5.0/macos/lib/QtSvg.framework/Resources/QtSvg.prl:
/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Resources/QtGui.prl:
/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile StrategyViewer.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug QMAKE_APPLE_DEVICE_ARCHS=arm64

qmake_all: FORCE

StrategyViewer.app/Contents/PkgInfo: 
	@test -d StrategyViewer.app/Contents || mkdir -p StrategyViewer.app/Contents
	@$(DEL_FILE) StrategyViewer.app/Contents/PkgInfo
	@echo "APPL????" > StrategyViewer.app/Contents/PkgInfo
StrategyViewer.app/Contents/Resources/empty.lproj: 
	@test -d StrategyViewer.app/Contents/Resources || mkdir -p StrategyViewer.app/Contents/Resources
	@touch StrategyViewer.app/Contents/Resources/empty.lproj
	
StrategyViewer.app/Contents/Info.plist: 
	@test -d StrategyViewer.app/Contents || mkdir -p StrategyViewer.app/Contents
	@$(DEL_FILE) StrategyViewer.app/Contents/Info.plist
	@plutil -convert xml1 -o - /Users/juliensolbach/Qt/6.5.0/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.StrategyViewer,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.StrategyViewer,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,StrategyViewer,g" -e "s,@LIBRARY@,StrategyViewer,g" -e "s,\$${EXECUTABLE_NAME},StrategyViewer,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >StrategyViewer.app/Contents/Info.plist

all: Makefile \
		StrategyViewer.app/Contents/PkgInfo \
		StrategyViewer.app/Contents/Resources/empty.lproj \
		StrategyViewer.app/Contents/Info.plist StrategyViewer.app/Contents/MacOS/StrategyViewer

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ui.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../LIBS/common/shared_types.hpp jsonhelperfunctions.h link.h mainwindow.h node.h playground.h robot.h toolboxscene.h $(DISTDIR)/
	$(COPY_FILE) --parents jsonhelperfunctions.cpp link.cpp main.cpp mainwindow.cpp node.cpp playground.cpp robot.cpp toolboxscene.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r StrategyViewer.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug QMAKE_APPLE_DEVICE_ARCHS=arm64

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_ui.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ui.cpp
qrc_ui.cpp: ui.qrc \
		/Users/juliensolbach/Qt/6.5.0/macos/libexec/rcc \
		Images/robot_top.png \
		Images/potibot.png \
		Images/vinyle_table_2023.png
	/Users/juliensolbach/Qt/6.5.0/macos/libexec/rcc -name ui --no-zstd ui.qrc -o qrc_ui.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/data/dummy.cpp
	/Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=11.0 -Wall -Wextra -dM -E -o moc_predefs.h /Users/juliensolbach/Qt/6.5.0/macos/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_link.cpp moc_mainwindow.cpp moc_node.cpp moc_playground.cpp moc_toolboxscene.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_link.cpp moc_mainwindow.cpp moc_node.cpp moc_playground.cpp moc_toolboxscene.cpp
moc_link.cpp: link.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSimpleTextItem \
		moc_predefs.h \
		/Users/juliensolbach/Qt/6.5.0/macos/libexec/moc
	/Users/juliensolbach/Qt/6.5.0/macos/libexec/moc $(DEFINES) --include /Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/StrategyViewer/moc_predefs.h -I/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/StrategyViewer -I/Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/LIBS/common -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtSvg.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1 -I/Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.3/include -I/Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include -I/Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/juliensolbach/Qt/6.5.0/macos/lib link.h -o moc_link.cpp

moc_mainwindow.cpp: mainwindow.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		toolboxscene.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QDragMoveEvent \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonDocument \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsondocument.h \
		playground.h \
		../LIBS/common/shared_types.hpp \
		robot.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		node.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonArray \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonarray.h \
		link.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSimpleTextItem \
		moc_predefs.h \
		/Users/juliensolbach/Qt/6.5.0/macos/libexec/moc
	/Users/juliensolbach/Qt/6.5.0/macos/libexec/moc $(DEFINES) --include /Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/StrategyViewer/moc_predefs.h -I/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/StrategyViewer -I/Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/LIBS/common -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtSvg.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1 -I/Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.3/include -I/Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include -I/Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/juliensolbach/Qt/6.5.0/macos/lib mainwindow.h -o moc_mainwindow.cpp

moc_node.cpp: node.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonArray \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonarray.h \
		link.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSimpleTextItem \
		moc_predefs.h \
		/Users/juliensolbach/Qt/6.5.0/macos/libexec/moc
	/Users/juliensolbach/Qt/6.5.0/macos/libexec/moc $(DEFINES) --include /Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/StrategyViewer/moc_predefs.h -I/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/StrategyViewer -I/Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/LIBS/common -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtSvg.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1 -I/Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.3/include -I/Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include -I/Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/juliensolbach/Qt/6.5.0/macos/lib node.h -o moc_node.cpp

moc_playground.cpp: playground.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../LIBS/common/shared_types.hpp \
		robot.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		node.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonArray \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonarray.h \
		link.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSimpleTextItem \
		moc_predefs.h \
		/Users/juliensolbach/Qt/6.5.0/macos/libexec/moc
	/Users/juliensolbach/Qt/6.5.0/macos/libexec/moc $(DEFINES) --include /Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/StrategyViewer/moc_predefs.h -I/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/StrategyViewer -I/Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/LIBS/common -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtSvg.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1 -I/Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.3/include -I/Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include -I/Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/juliensolbach/Qt/6.5.0/macos/lib playground.h -o moc_playground.cpp

moc_toolboxscene.cpp: toolboxscene.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QDragMoveEvent \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h \
		moc_predefs.h \
		/Users/juliensolbach/Qt/6.5.0/macos/libexec/moc
	/Users/juliensolbach/Qt/6.5.0/macos/libexec/moc $(DEFINES) --include /Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/StrategyViewer/moc_predefs.h -I/Users/juliensolbach/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/StrategyViewer -I/Users/juliensolbach/Documents/Workspace/VRAC/eurobotsoftware2023/LIBS/common -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtSvg.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1 -I/Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.3/include -I/Applications/Xcode_13_0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include -I/Applications/Xcode_13_0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/juliensolbach/Qt/6.5.0/macos/lib toolboxscene.h -o moc_toolboxscene.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/Users/juliensolbach/Qt/6.5.0/macos/libexec/uic
	/Users/juliensolbach/Qt/6.5.0/macos/libexec/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

jsonhelperfunctions.o: jsonhelperfunctions.cpp jsonhelperfunctions.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonArray \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonarray.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonDocument \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsondocument.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonValue \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonvalue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jsonhelperfunctions.o jsonhelperfunctions.cpp

link.o: link.cpp link.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSimpleTextItem \
		node.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonArray \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonarray.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPainter \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QEvent \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qcoreevent.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QCursor \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/qcursor.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QLayout \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qlayout.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QComboBox \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qcombobox.h \
		jsonhelperfunctions.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonDocument \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsondocument.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonValue \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonvalue.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMenu \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o link.o link.cpp

main.o: main.cpp mainwindow.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		toolboxscene.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QDragMoveEvent \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonDocument \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsondocument.h \
		playground.h \
		../LIBS/common/shared_types.hpp \
		robot.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		node.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonArray \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonarray.h \
		link.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSimpleTextItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QApplication \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		toolboxscene.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QDragMoveEvent \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonDocument \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsondocument.h \
		playground.h \
		../LIBS/common/shared_types.hpp \
		robot.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		node.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonArray \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonarray.h \
		link.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSimpleTextItem \
		ui_mainwindow.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPainter \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGridLayout \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QStyleOption \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qstyleoption.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QToolButton \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QFile \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qfile.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QDir \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qdir.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QFileDialog \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QFileInfo \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qfileinfo.h \
		jsonhelperfunctions.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonValue \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonvalue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

node.o: node.cpp node.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonArray \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonarray.h \
		link.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSimpleTextItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPainter \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QTextCursor \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/qtextcursor.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QApplication \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qapplication.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMenu \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmenu.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QCheckBox \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qcheckbox.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QSpinBox \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qspinbox.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QComboBox \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qcombobox.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVariantList \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvariantlist.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QStringList \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qstringlist.h \
		jsonhelperfunctions.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonDocument \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsondocument.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonValue \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonvalue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o node.cpp

playground.o: playground.cpp playground.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../LIBS/common/shared_types.hpp \
		robot.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		node.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonArray \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonarray.h \
		link.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSimpleTextItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtSvg.framework/Headers/QSvgRenderer \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtSvg.framework/Headers/qsvgrenderer.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPainter \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsPathItem
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playground.o playground.cpp

robot.o: robot.cpp robot.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsPixmapItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../LIBS/common/shared_types.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o robot.o robot.cpp

toolboxscene.o: toolboxscene.cpp toolboxscene.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QDragMoveEvent \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSceneDragDropEvent \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QMimeData \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qmimedata.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QIODevice \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qiodevice.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtSvg.framework/Headers/QSvgRenderer \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtSvg.framework/Headers/qsvgrenderer.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPainter \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		node.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/QJsonArray \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtCore.framework/Headers/qjsonarray.h \
		link.h \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		/Users/juliensolbach/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QGraphicsSimpleTextItem
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolboxscene.o toolboxscene.cpp

qrc_ui.o: qrc_ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ui.o qrc_ui.cpp

moc_link.o: moc_link.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_link.o moc_link.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_node.o: moc_node.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_node.o moc_node.cpp

moc_playground.o: moc_playground.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_playground.o moc_playground.cpp

moc_toolboxscene.o: moc_toolboxscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolboxscene.o moc_toolboxscene.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/StrategyViewer/bin || mkdir -p $(INSTALL_ROOT)/opt/StrategyViewer/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/StrategyViewer/bin/StrategyViewer.app
	
	$(QINSTALL) StrategyViewer.app $(INSTALL_ROOT)/opt/StrategyViewer/bin/StrategyViewer.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/StrategyViewer/bin/StrategyViewer.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/StrategyViewer/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

